<?php
$e2g_lang['english'] = array (
    'add_err' => 'not added.',
    'added' => 'added.',
    'back' => 'Back',
    'comment' => '&lt;p&gt;Install script will automatically create snippet and all tables in db&lt;br /&gt;&lt;br /&gt;If you are upgrading from the previous version installation (&amp;lt;1.3.6-alpha2), &lt;strong style=&quot;color: red;&quot;&gt; this will also RENAME&lt;/strong&gt; all the folder&#039;s and file&#039;s names to their original names.&lt;br /&gt;Backing up your SQL&#039;s and Gallery&#039;s files &lt;strong style=&quot;color: red;&quot;&gt;BEFORE UPGRADING&lt;/strong&gt; is highly encouraged.&lt;br /&gt;You have been warned!&lt;/p&gt;',
    'comment1' => '&lt;p&gt;Path to folder, &lt;strong class=&quot;warning&quot;&gt;with trailing slash&lt;/strong&gt;, where images will be stored.&lt;br /&gt;e.g. &lt;strong&gt;assets/images/gallery/&lt;/strong&gt;&lt;/p&gt;',
    'create_dir_err' => 'Couldn&#039;t create folder',
    'create_err' => 'could not be created.',
    'created' => 'created successfully.',
    'credit_lang_file' => 'Language file credit',
    'credit_lang_file_author' => 'Cx2, Temus, goldsky',
    'credit_lang_file_date' => 'October 6, 2010',
    'credit_lang_file_version' => '2.1',
    'data' => 'Data',
    'data_updated_err' => ' data(s) update failed',
    'data_updated_suc' => ' data(s) updated',
    'del_inst_dir' => 'Delete INSTALL folder',
    'dir_created' => 'Folder is created',
    'dir_exists' => 'Folder exists',
    'empty_dir' => 'folder is not set',
    'field' => 'Field',
    'install' => 'Installation',
    'mod_update_err' => 'Couldn&#039;t update module',
    'mod_updated' => 'Module is updated',
    'ok' => 'Install',
    'path' => 'Path',
    'plugin_added' => 'Plugin created',
    'plugin_add_err' => 'Could not add plugin',
    'mod_update_err' => 'Couldn&#039;t update plugin',
    'plugin_updated' => 'Plugin is updated',
    'rename' => 'renamed.',
    'rename_err' => 'not renamed.',
    'restore_err' => 'There was an error while trying to restore',
    'restore_suc' => 'Gallery&#039;s names restored',
    'snippet_add_err' => 'Couldn&#039;t create snippet',
    'snippet_added' => 'Snippet created',
    'snippet_update_err' => 'Couldn&#039;t update snippet',
    'snippet_updated' => 'Snippet is updated',
    'submit' => 'Save',
    'success' => 'Installed successfully',
    'system_check' => 'System check',
    'table' => 'Table',
    'upgraded' => 'upgraded successfully.',
    'upgrade_err' => 'could not be upgraded.'
);
