<?php
$e2g_lang['english'] = array (
    'captcha_err' => 'Invalid captcha code',
    'code' => 'Code',
    'comment_add' => 'Add Comment',
    'comment_add_err' => 'There was an error while trying to post comment',
    'comment_added' => 'Comment is added',
    'credit_lang_file' => 'Language file credit',
    'credit_lang_file_author' => 'Cx2, Temus, goldsky',
    'credit_lang_file_date' => 'October 6, 2010',
    'credit_lang_file_version' => '2.1',
    'email' => 'Email',
    'email_err' => 'Invalid email',
    'comment_empty_name_comment' => 'You must enter your name and comment',
    'comment_empty_name' => 'You must enter your name',
    'comment_empty_comment' => 'You must enter any comment',
    'name' => 'Name',
    'notify' => 'Notify me the replies',
    'pages' => 'Pages',
    'send_btn' => 'Post comment',
    'submit' => 'Save',
    'title' => 'Comments',
    'usercomment' => 'Your Comment',
    'waitforapproval' => 'Your comment will wait for approval'
);
