<?php
$e2g_lang['english'] = array (
        'add_err' => 'not added.',
        'added' => 'added.',
        'system_check' => 'System check',
        'back' => 'Back',
        'comment' => 'Install script will automatically create snippet and all tables in db&lt;br /&gt;&lt;br /&gt;If you are upgrading from the previous version installation (&lt;1.3.6-alpha2), &lt;b style=&quot;color:red;&quot;&gt; this will also RENAME&lt;/b&gt; all the folder&#039;s and file&#039;s names to their original names.&lt;br /&gt;Backing up your SQL&#039;s and Gallery&#039;s files &lt;b style=&quot;color:red;&quot;&gt;BEFORE UPGRADING&lt;/b&gt; is highly encouraged.&lt;br /&gt;You have been warned!',
        'comment1' => 'Path to folder, &lt;b class=\&quot;warning\&quot;&gt;with trailing slash&lt;/b&gt;, where images will be saved.&lt;br /&gt;e.g. assets/gallery/.',
        'create_dir_err' => 'Can&#039;t create folder',
        'create_err' => 'not created.',
        'created' => 'created successfully.',
        'data' => 'Data',
        'del_inst_dir' => 'Delete INSTALL folder',
        'dir_created' => 'Folder created',
        'empty_dir' => 'folder not set',
        'field' => 'Field',
        'mod_update_err' => 'Can&#039;t update module',
        'mod_updated' => 'Module updated',
        'ok' => 'Install',
        'path' => 'Path',
        'rename' => 'renamed.',
        'rename_err' => 'not renamed.',
        'restore_err' => 'There was an error while trying to restore',
        'restore_suc' => 'Gallery&#039;s names restored',
        'snippet_add_err' => 'Can&#039;t create snippet',
        'snippet_added' => 'Snippet created',
        'snippet_update_err' => 'Can&#039;t update snippet',
        'snippet_updated' => 'Snippet updated',
        'success' => 'Install successful',
        'table' => 'Table',
        'upgraded' => 'upgraded successfully.',
);
?>