<?php
$e2g_lang['german'] = array (
    'add_err' => 'nicht hinzugefügt.',
    'added' => 'hinzugefügt.',
    'back' => 'zurück',
    'comment' => '&lt;p&gt;Install script will automatically create snippet and all tables in db&lt;br /&gt;&lt;br /&gt;If you are upgrading from the previous version installation (&amp;lt;1.3.6-alpha2), &lt;strong style=&quot;color: red;&quot;&gt; this will also RENAME&lt;/strong&gt; all the folder&#039;s and file&#039;s names to their original names.&lt;br /&gt;Backing up your SQL&#039;s and Gallery&#039;s files &lt;strong style=&quot;color: red;&quot;&gt;BEFORE UPGRADING&lt;/strong&gt; is highly encouraged.&lt;br /&gt;You have been warned!&lt;/p&gt;',
    'comment1' => '&lt;p&gt;Pfad zum Verzeichnis, &lt;strong class=&quot;warning&quot;&gt;with trailing slash&lt;/strong&gt;, where images will be stored.&lt;br /&gt;e.g. &lt;strong&gt;assets/images/gallery/&lt;/strong&gt;&lt;/p&gt;',
    'create_dir_err' => 'Konnte Verzeichnis nicht erstellen',
    'create_err' => 'konnte nicht erstellt werden.',
    'created' => 'erfolreich erstellt.',
    'credit_lang_file' => 'Sprachdatei durch',
    'credit_lang_file_author' => 'Beat Beer, stardesign',
    'credit_lang_file_date' => 'Februar 2012',
    'credit_lang_file_version' => '2.1',
    'data' => 'Data',
    'data_updated_err' => ' data(s) update gescheitert',
    'data_updated_suc' => ' data(s) aktualisiert',
    'del_inst_dir' => 'Install Verzeichnis löschen',
    'dir_created' => 'Verzeichnis wurde erstellt',
    'dir_exists' => 'Verzeichnis vorhanden',
    'empty_dir' => 'Verzeichnis nicht festgelegt',
    'field' => 'Feld',
    'install' => 'Installation',
    'mod_update_err' => 'Konnte Modul nicht aktualisieren',
    'mod_updated' => 'Modul aktualisiert',
    'ok' => 'Installieren',
    'path' => 'Pfad',
    'plugin_added' => 'Plugin erstellt',
    'plugin_add_err' => 'Konnte Plugin nicht hizufügen',
    'mod_update_err' => 'Konnte Plugin nicht aktualisieren',
    'plugin_updated' => 'Plugin aktualisiert',
    'rename' => 'umbenannt.',
    'rename_err' => 'nicht umbenannt.',
    'restore_err' => 'Fehler bei der wiederherstellung',
    'restore_suc' => 'Galeriename wieder hergestellt',
    'snippet_add_err' => 'Konnte Snippet nicht erstellen',
    'snippet_added' => 'Snippet erstellt',
    'snippet_update_err' => 'Konte Snippet nicht aktualisieren',
    'snippet_updated' => 'Snippet aktualisiert',
    'submit' => 'Sichern',
    'success' => 'Erfolreich installiert',
    'system_check' => 'System check',
    'table' => 'Tabelle',
    'upgraded' => 'erfolgreich aktualisiert.',
    'upgrade_err' => 'konnte nicht aktualisiert werden.'
);
