<?php
$e2g_lang['german'] = array (
    'captcha_err' => 'Ungültiger Captcha Code',
    'code' => 'Code',
    'comment_add' => 'Kommentar hinzufügen',
    'comment_add_err' => 'Konnte Kommentar nicht speichern',
    'comment_added' => 'Kommentar hinzugefügt',
    'comment_empty_comment' => 'Bitte Kommentar eingeben',
    'comment_empty_name' => 'Bitte Namen eingeben',
    'comment_empty_name_comment' => 'Name und Kommentar müssen eingegeben werden',
    'credit_lang_file' => 'Deutsche Übersetzung',
    'credit_lang_file_author' => 'Beat Beer, stardesign',
    'credit_lang_file_date' => '15. Februar 2012',
    'credit_lang_file_version' => '2.1',
    'email' => 'Email',
    'email_err' => 'Ungültige Email',
    'name' => 'Name',
    'notify' => 'Benachrichtigung bei Kommentaren',
    'pages' => 'Seiten',
    'send_btn' => 'Kommentar eingeben',
    'submit' => 'Save',
    'title' => 'Kommentare',
    'usercomment' => 'Dein Kommentar',
    'waitforapproval' => 'Kommentar wartet auf Freigabe'
);
