<?php
$e2g_lang['polish-utf8'] = array (
        '_thumb_err' => 'Nie można utworzyć folderu &quot;_thumbnails&quot;.',
        'add' => 'Dodawać',
        'add_to_db' => 'Dodaj do bazy danych',
        'archive' => 'Archiwum ZIP',
        'asc' => 'rosnąco',
        'author' => 'Autor',
        'bottom' => 'dół',
        'btn_field_add' => 'Załaduj więcej',
        'cache_clean' => 'Cache został wyczyszczony',
        'cache_clean_err' => 'Wystąpił błąd podczas próby wyczyszczenia cache&#039;u',
        'cancel' => 'Anuluj',
        'cat_name_len' => 'maksymalna długość nazwy folderu',
        'cat_name_len_cfg_desc' => 'Maksymalna długość nazwy folderu',
        'center' => 'środek',
        'char_bad' => 'Nieprawidłowe znaki dla używanego systemu plików.',
        'char_limitation' => '&lt;p&gt;Nazwy plik&amp;oacute;w w archiwum ZIP muszą się składać wyłącznie ze standardowych znak&amp;oacute;w łacińskich (bez znak&amp;oacute;w diakrytycznych) w przeciwnym wypadku wystąpią błędy podczas jego ładowania.&lt;br /&gt;Znaki kodowane w UTF-8 będą zignorowane lub zastąpione przez najbliższy im znak standardowy.&lt;/p&gt;',
        'charset' => 'UTF-8',
        'clean_cache' => 'Wyczyść cache',
        'colls' => 'Ilość komumn',
        'colls_cfg_desc' => 'Ilość kolumn w których wyświetlane są miniaturki.',
        'comment' => 'Komentarz',
        'comment_add' => 'Dodaj komentarz',
        'comment_add_err' => 'Wystąpił błąd podczas próby dodania komentarza.',
        'comment_added' => 'Komentarz został dodany.',
        'comments' => 'Komentarze',
        'comments_all_title' => 'Wszystkie komentarze',
        'comments_cnt' => 'liczba komentarzy',
        'comments_hidden_title' => 'Ukryte komentarze',
        'comments_row' => 'Wiersz komentarza',
        'commentsmgr' => 'Zarządzanie komentarzami',
        'config' => 'Konfiguracja',
        'credit_lang_file' => 'Language file credit',
        'credit_lang_file_author' => 'fixedmachine',
        'css' => 'CSS',
        'date' => 'Data',
        'date_added' => 'data',
        'delete' => 'Usuń',
        'desc' => 'malejąco',
        'description' => 'Opis',
        'dir' => 'folder',
        'dir_add_err' => 'Wystąpił błąd podczas próby utworzenia folderu',
        'dir_added' => 'Folder utworzony pomyślnie',
        'dir_cfg_desc' => 'Ścieżka do folderu &lt;b class=&quot;warning&quot;&gt;zakończona slashem&lt;/b&gt;, np.: assets/easy2gallery/.',
        'dir_create' => 'Nowy folder',
        'dir_create_err' => 'Nie można utworzyć folderu',
        'dir_created' => 'folder utworzony pomyślnie',
        'dir_delete' => 'folder usunięty',
        'dir_delete_err' => 'Nie można usunąć folderu.',
        'dir_delete_fdb' => 'folder usunięty wyłącznie z bazy danych',
        'dir_delete_fhdd' => 'folder usunięty wyłącznie z dysku',
        'dirs_delete_err' => 'Nie można usunąć folderów.',
        'dirs_deleted' => 'foldery pomyślnie usunięte',
        'dirs_deleted_fdb' => 'foldery pomyślnie usunięte z bazy danych',
        'dirs_deleted_fhdd' => 'foldery pomyślnie usunięte z dysku',
        'dpath_err' => 'ścieżka lub id folderu jest niezdefiniowane',
        'e2g_debug_cfg_desc' => 'Tryb debugowania.',
        'e2g_encode_cfg_desc' => 'Folder w którym znajduje się edytor TinyMCE, np.: tinymce3241 (MODx Evolution 1.0.2)',
        'ecl' => 'Ilość komentarzy na stronę',
        'ecl_cfg_desc' => 'Ilość komentarzy wyświetlanych na poszczególnych stronach.',
        'edit' => 'Edytuj',
        'editing' => 'Edytuj właściwości',
        'email' => 'Email',
        'empty' => 'pusty',
        'empty_name_comment' => 'Musisz wpisać swój podpis oraz komentarz.',
        'enter_dirname' => 'Wpisz nazwę folderu',
        'enter_new_dirname' => 'Zmień nazwę folderu',
        'extension_valid' => 'Akceptowane rozszerzenia to:',
        'file' => 'Plik',
        'file_add_err' => 'Nie można dodać pliku.',
        'file_added' => 'Plik został dodany.',
        'file_delete' => 'plik usunięty',
        'file_delete_err' => 'Nie można usunąć pliku',
        'file_delete_fdb' => 'plik usunięty wyłącznie z bazy danych',
        'file_delete_fhdd' => 'plik usunięty wyłącznie z dysku',
        'file_rename' => 'Zmień nazwę pliku',
        'file_rename_err' => 'Nie można zmienić nazwy pliku.',
        'filename' => 'nazwa pliku',
        'files' => 'pliku',
        'files_delete_err' => 'Nie można usunąć plików.',
        'files_deleted' => 'pliki usunięte pomyślnie',
        'files_deleted_fdb' => 'pliki pomyślnie usunięte z bazy danych',
        'files_deleted_fhdd' => 'pliki pomyślnie usunięte z dysku',
        'files_uploaded' => 'pliki załadowane pomyślnie',
        'fpath_err' => 'ścieżka lub id obrazu jest niezdefiniowane',
        'gallery' => 'Galeria',
        'glib' => 'Biblioteka JS',
        'glib_cfg_desc' => 'Biblioteka graficzna',
        'grid_cfg_desc' => 'Wykorzystywanie tabel do wyświetlania miniaturek albo nie.',
        'h' => 'Wysokość',
        'h_cfg_desc' => 'Maksymalna wysokość w pikselach. Większe obrazy będą automatycznie skalowane.&lt;br /&gt; &lt;b&gt;0 - brak limitu&lt;/b&gt;.',
        'h_thumb_cfg_desc' => 'Wysokość miniaturek w pikselach (px)',
        'help' => 'Pomoc',
        'help_moreinfo_content' => '&lt;p&gt;&lt;a href=&quot;http://e2g.info/documentation.htm&quot; target=&quot;_blank&quot;&gt;&lt;strong&gt;Dokumentacja&lt;/strong&gt;&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;a href=&quot;http://e2g.info/&quot; target=&quot;_blank&quot;&gt;Oficjalna strona Easy 2 Gallery&lt;/a&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;a href=&quot;http://wiki.modxcms.com/index.php/Easy2gallery&quot; target=&quot;_blank&quot;&gt;Easy 2 Gallery WIKI&lt;/a&gt;&lt;/strong&gt;&lt;/p&gt;',
        'help_moreinfo_title' => 'Więcej informacji',
        'help_params_title' => 'Parametry',
        'help_tpl_content' => '&lt;h2&gt;Parametry szablon&amp;oacute;w&lt;/h2&gt;
&lt;p&gt;&lt;strong&gt;glib&lt;/strong&gt; - biblioteka JavaScript.&lt;br /&gt; Wartość domyślna: highslide&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;css&lt;/strong&gt; - style CSS.&lt;br /&gt; Nazwa &quot;chunka&quot; albo ścieżka do pliku z szablonem.&lt;br /&gt; Wartość domyślna: assets/modules/easy2/templates/style.css&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;tpl&lt;/strong&gt; - szablon galerii.&lt;br /&gt; Nazwa &quot;chunka&quot; albo ścieżka do pliku z szablonem.&lt;br /&gt; Wartość domyślna: assets/modules/easy2/templates/gallery.htm&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;dir_tpl&lt;/strong&gt; - szablon folderu.&lt;br /&gt; Nazwa &quot;chunka&quot; albo ścieżka do pliku z szablonem.&lt;br /&gt; Wartość domyślna: assets/modules/easy2/templates/directory.htm&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;thumb_tpl&lt;/strong&gt; - szablon miniaturki.&lt;br /&gt; Nazwa &quot;chunka&quot; albo ścieżka do pliku z szablonem.&lt;br /&gt; Wartość domyślna: assets/modules/easy2/templates/thumbnail.htm&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;rand_tpl&lt;/strong&gt; - szablon dla obrazk&amp;oacute;w wyświetlanych losowo&lt;br /&gt; Nazwa &quot;chunka&quot; albo ścieżka do pliku z szablonem.&lt;br /&gt; Wartość domyślna: assets/modules/easy2/templates/random_thumbnail.htm&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;comments_tpl&lt;/strong&gt; - szablon dla komentarzy.&lt;br /&gt; Nazwa &quot;chunka&quot; albo ścieżka do pliku, relatywna do comments.easy2gallery.php.&lt;br /&gt; Wartość domyślna: assets/modules/easy2/templates/comments.htm&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;comments_row_tpl&lt;/strong&gt; - szablon wiersza komentarza.&lt;br /&gt; Nazwa &quot;chunka&quot; albo ścieżka do pliku, relatywna do comments.easy2gallery.php.&lt;br /&gt; Wartość domyślna: assets/modules/easy2/templates/comments_row.htm&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;h2&gt;Opis placeholder&amp;oacute;w&lt;/h2&gt;
&lt;h3&gt;Galeria:&lt;/h3&gt;
&lt;p&gt;&lt;strong&gt;[+easy2:cat_name+]&lt;/strong&gt; - nazwa aktualnego folderu&lt;br /&gt; &lt;strong&gt;[+easy2:back+]&lt;/strong&gt; - link powrotu do poziomu bazowego (parent)&lt;br /&gt; &lt;strong&gt;[+easy2:content+]&lt;/strong&gt; - zawartość galerii&lt;br /&gt; &lt;strong&gt;[+easy2:pages+]&lt;/strong&gt; - paginacja&lt;/p&gt;
&lt;h3&gt;Foldery:&lt;/h3&gt;
&lt;p&gt;&lt;strong&gt;[+easy2:cat_name+]&lt;/strong&gt; - nazwa folderu&lt;br /&gt; &lt;strong&gt;[+easy2:cat_id+]&lt;/strong&gt; - id folderu&lt;br /&gt; &lt;strong&gt;[+easy2:parent_id+]&lt;/strong&gt; - id folderu w kt&amp;oacute;rym znajduje się bierzący folder&lt;br /&gt; &lt;strong&gt;[+easy2:cat_level+]&lt;/strong&gt; - poziom zagnieżdżenia&lt;br /&gt; &lt;strong&gt;[+easy2:count+]&lt;/strong&gt; - liczba plik&amp;oacute;w&lt;/p&gt;
&lt;h3&gt;Miniaturki:&lt;/h3&gt;
&lt;p&gt;&lt;strong&gt;[+easy2:src+]&lt;/strong&gt; - ścieżka do miniaturki&lt;br /&gt; &lt;strong&gt;[+easy2:w+]&lt;/strong&gt; - szerokość miniaturki&lt;br /&gt; &lt;strong&gt;[+easy2:h+]&lt;/strong&gt; - wysokość miniaturki&lt;br /&gt; &lt;strong&gt;[+easy2:id+]&lt;/strong&gt; - id obrazka&lt;br /&gt; &lt;strong&gt;[+easy2:name+]&lt;/strong&gt; - nazwa obrazka (jeśli &amp;gt; name_len to wtedy długość = name_len-2)&lt;br /&gt; &lt;strong&gt;[+easy2:title+]&lt;/strong&gt; - nazwa obrazka (pełna nazwa)&lt;br /&gt; &lt;strong&gt;[+easy2:description+]&lt;/strong&gt; - opis obrazka&lt;br /&gt; &lt;strong&gt;[+easy2:filename+]&lt;/strong&gt; - nazwa pliku obrazka&lt;br /&gt; &lt;strong&gt;[+easy2:size+]&lt;/strong&gt; - rozmiar pliku obrazka (bytes)&lt;br /&gt; &lt;strong&gt;[+easy2:comments+]&lt;/strong&gt; - ilość komentarzy dla obrazka&lt;br /&gt; &lt;strong&gt;[+easy2:date_added+]&lt;/strong&gt; - data dodania&lt;br /&gt; &lt;strong&gt;[+easy2:last_modified+]&lt;/strong&gt; - data modyfikacji&lt;br /&gt; &lt;strong&gt;[+easy2:dir_id+]&lt;/strong&gt; - id folderu&lt;/p&gt;
&lt;h3&gt;Komentarze (wiersz):&lt;/h3&gt;
&lt;p&gt;&lt;strong&gt;[+easy2:id+]&lt;/strong&gt; - id komentarza&lt;br /&gt; &lt;strong&gt;[+easy2:file_id+]&lt;/strong&gt; - id pliku&lt;br /&gt; &lt;strong&gt;[+easy2:author+]&lt;/strong&gt; - podpis autora komentarza&lt;br /&gt; &lt;strong&gt;[+easy2:email+]&lt;/strong&gt; - email autora komentarza&lt;br /&gt; &lt;strong&gt;[+easy2:name_w_mail+]&lt;/strong&gt; - jeśli email jest podany &quot;&lt;a href=&quot;mailto:[+easy2:email+]&quot;&gt;[+easy2:author+]&lt;/a&gt;&quot;, w przeciwnym wypadku &quot;[+easy2:author+]&quot;&lt;br /&gt; &lt;strong&gt;[+easy2:comment+]&lt;/strong&gt; - treść komentarza&lt;br /&gt; &lt;strong&gt;[+easy2:date_added+]&lt;/strong&gt; - data dodania komentarza&lt;br /&gt; &lt;strong&gt;[+easy2:last_modified+]&lt;/strong&gt; - data modyfikacji komentarza&lt;/p&gt;
&lt;h3&gt;Komentarze (formularz dodawania komentarza):&lt;/h3&gt;
&lt;p&gt;&lt;strong&gt;[+easy2:title+]&lt;/strong&gt; - tytuł strony (zdefiniowany w pliku langs/*.comments.php)&lt;br /&gt; &lt;strong&gt;[+easy2:body+]&lt;/strong&gt; - komentarze&lt;br /&gt; &lt;strong&gt;[+easy2:pages+]&lt;/strong&gt; - linki paginacji&lt;br /&gt; + ustawienia specyficzne dla danego języka: langs/*.comments.php&lt;/p&gt;',
        'help_tpl_title' => 'Szablony',
        'id_err' => 'nieprawidłowe id',
        'ignore' => 'Ignoruj',
        'image' => 'obrazek',
        'indexfile' => '&lt;h2&gt;Brak dostępu&lt;/h2&gt;Nie posiadasz praw dostępu do tego folderu',
        'info' => 'Właściwości',
        'inner' => 'przycięcie',
        'install' => 'Instalacja',
        'ip_address' => 'Adres IP',
        'ip_ignored_suc' => 'To IP jest od teraz ignorowane.',
        'ip_ignored_title' => 'Ignorowane adresy IP',
        'ip_unignored_suc' => 'To IP już nie jest ignorowane.',
        'last_modified' => 'data edycji',
        'left' => 'lewo',
        'limit' => 'Ilość obrazów na stronę',
        'limit_cfg_desc' => 'Ilość miniaturek wyświetlanych na poszczególnych stronach.',
        'modified' => 'Zmodyfikowano',
        'move' => 'Przenieś',
        'movetofolder' => 'Przenieś do folderu',
        'name' => 'Podpis',
        'name_len' => 'maksymalna długość nazwy miniaturki',
        'name_len_cfg_desc' => 'Maksymalna długość nazwy pliku',
        'off' => 'Wyłączone',
        'on' => 'Włączone',
        'actions' => 'Akcje',
        'order' => 'Sortuj miniaturki wg',
        'order2' => 'Sortuj foldery wg',
        'order2_cfg_desc' => 'Metoda sortowania folderów',
        'order_cfg_desc' => 'Metoda sortowania plików',
        'path' => 'Ścieżka',
        'post' => 'Wyślij',
        'random' => 'losowo',
        'recaptcha' => 'recaptcha',
        'remove' => 'Usuń',
        'resize' => 'skalowanie proporcjonalne',
        'resize_type' => 'Rodzaj skalowania miniaturek',
        'resize_type_cfg_desc' => '&lt;b&gt;Przycięcie:&lt;/b&gt; obraz zostaje przycięty do wymiarów miniaturki.&lt;br /&gt;&lt;b&gt;Skalowanie:&lt;/b&gt; obraz zostaje zeskalowany do rozmiarów miniaturki bez uwzględniania proporcji.&lt;br /&gt;&lt;b&gt;Skalowanie proporcjonalne:&lt;/b&gt; obraz zostaje zeskalowany do rozmiarów miniaturki z uwzględnieniem jego proporcji. Ewentualny naddatek zostaje wypełniony kolorem ustalonym poniżej.',
        'restore_err' => 'Wystąpił błąd podczas próby przywracania',
        'restore_suc' => 'Nazwa galerii została przywrócona',
        'right' => 'prawo',
        'save' => 'Zapisz',
        'settings_display' => 'Ustawienia wyświetlania',
        'settings_img' => 'Ustawienia obrazów',
        'settings_thumb' => 'Ustawienia miniaturek',
        'shrink' => 'skalowanie',
        'size' => 'Rozmiar',
        'synchro' => 'Synchronizuj',
        'synchro_err' => 'Wystąpił błąd podczas próby synchronizacji galerii',
        'synchro_suc' => 'Galeria została pomyślnie zsynchronizowana',
        'text' => 'tekst',
        'thbg_rgb' => 'Kolor tła miniaturki',
        'thbg_rgb_cfg_desc' => 'Biały to 255 255 255, czarny 0 0 0.',
        'thq' => 'Stopień kompresji',
        'thq_cfg_desc' => 'Stopień kompresji jpeg dla miniaturek od 0 do 100%.',
        'thumb' => 'miniaturka',
        'top' => 'góra',
        'tpl' => 'Szablony',
        'tpl_comments_cfg_desc' => 'Nazwa &quot;chunka&quot; albo ścieżka do pliku, &lt;b class=&quot;warning&quot;&gt;relatywna do comments.easy2gallery.php&lt;/b&gt;',
        'tpl_path_cfg_desc' => 'Nazwa ',
        'type' => 'typ',
        'type_err' => 'Niedozwolony typ pliku.',
        'uim_preview' => 'Podgląd',
        'uim_preview_err' => 'Podgląd&lt;br /&gt;niedostępny',
        'unignore' => 'Usuń z ignorowanych',
        'update' => 'Odśwież',
        'update_err' => 'zmiany nie zostały zapisane',
        'updated' => 'uaktualniono',
        'upload' => 'Załaduj',
        'upload_dir' => 'Załaduj zdjęcia do folderu',
        'upload_err' => 'Nie można załadować pliku.',
        'upload_image' => 'Ładowanie plików',
        'w' => 'Szerokość',
        'w_cfg_desc' => 'Maksymalna szerokość w pikselach. Większe obrazy będą automatycznie skalowane.&lt;br /&gt; &lt;b&gt;0 - brak limitu&lt;/b&gt;.',
        'w_thumb_cfg_desc' => 'Szerokość miniaturek w pikselach (px)',
        'watermark_horpos' => 'Pozycja w poziomie',
        'watermark_horpos_cfg_desc' => 'Pozycja znaku wodnego w poziomie.',
        'watermark_text_path_cfg_desc' => 'Tekst dla znaku wodnego lub ścieżka do obrazu znaku wodnego.',
        'watermark_textpath' => 'tekst/ścieżka',
        'watermark_type_cfg_desc' => 'Typ znaku wodnego. Tekst albo obrazek.',
        'watermark_verpos' => 'Pozycja w pionie',
        'watermark_verpos_cfg_desc' => 'Pozycja znaku wodnego w pionie.',
        'watermarks' => 'Znaki wodne',
        'withselected' => 'Zaznaczone',
);
?>