<?php
$e2g_lang['russian-UTF8'] = array (
    'add_err' => 'не добавлены.',
    'added' => 'добавлены.',
    'back' => 'Назад',
    'comment' => '&lt;p&gt;Установщик сам создаст все необходимые таблицы в БД и сниппет для установки галереи на страницы сайта.&lt;br /&gt;&lt;br /&gt;Если вы обновляетесь с предыдущей версии (&amp;lt;1.3.6-alpha2), &lt;strong style=&quot;color: red;&quot;&gt; установщик также ПЕРЕИМЕНУЕТ&lt;/strong&gt; названия всех файлов и папок на исходные.&lt;br /&gt;Строго рекомендуется создать резервную копию файлов &lt;strong style=&quot;color: red;&quot;&gt;ДО ОБНОВЛЕНИЯ&lt;/strong&gt;.&lt;br /&gt;Вас предупредили!&lt;/p&gt;',
    'comment1' => '&lt;p&gt;Путь к папке, &lt;strong class=&quot;\&amp;quot;warning\&amp;quot;&quot;&gt;со слэшем в конце&lt;/strong&gt;, относительно корня сайта, в которую будут сохраняться изображения.&lt;br /&gt;e.g. assets/images/gallery/&lt;/p&gt;',
    'create_dir_err' => 'Не удалось создать папку',
    'create_err' => 'не создана.',
    'created' => 'успешно создана.',
    'credit_lang_file_author' => 'Cx2, Temus',
    'credit_lang_file_date' => 'October 6, 2010',
    'credit_lang_file_version' => '2.1',
    'data' => 'Данные в таблицу',
    'data_updated_err' => 'Невозможно обновить данные',
    'data_updated_suc' => 'Данные обновлены',
    'del_inst_dir' => 'Удалить установочные файлы',
    'dir_created' => 'Папка создана',
    'dir_exists' => 'Папка существует',
    'empty_dir' => 'Не указана папка',
    'field' => 'Поле',
    'mod_update_err' => 'Не удалось обновить код модуля',
    'mod_updated' => 'Модуль обновлен',
    'ok' => 'Установить',
    'path' => 'Путь',
    'plugin_add_err' => 'Невозможно добавить плагин',
    'plugin_added' => 'Плагин создан',
    'plugin_updated' => 'Плагин обновлен',
    'rename' => 'переименована.',
    'rename_err' => 'не переименована.',
    'restore_err' => 'При попытке восстановления имен возникли ошибки',
    'restore_suc' => 'Исходные имена восстановлены',
    'snippet_add_err' => 'Не удалось создать сниппет',
    'snippet_added' => 'Сниппет создан',
    'snippet_update_err' => 'Не удалось обновить сниппет',
    'snippet_updated' => 'Сниппет обновлен',
    'submit' => 'Save',
    'success' => 'Установка завершена',
    'system_check' => 'Проверка системы',
    'table' => 'Таблица',
    'upgrade_err' => 'Невозможно обновить',
    'upgraded' => 'Обновление завершено.'
);
