<?php
$e2g_lang['spanish'] = array (
        'add_err' => 'no ha sido a&ntilde;adido.',
        'added' => 'a&ntilde;adido.',     
        'back' => 'Atr&aacute;s',
        'comment' => 'El scripto de instalaci&oacute;n crear&aacute; autom&aacute;ticamente Snippet y todas las tablas del db. &lt;br /&gt;&lt;br /&gt; Si est&aacute; actualizando desde la versi&oacute;n anterior de instalaci&oacute;n (&lt;1.3.6-alpha2), &lt;b style=&quot;color:red;&quot;&gt; esto tambi&eacute;n Cambiar&aacute; el Nombre&lt;/b&gt; de todas las carpetas y nombres de archivos a sus nombres originales.&lt;br /&gt;Haciendo copias de seguridad de db SQL y los archivos de la Galer&iacute;a &lt;b style=&quot;color:red;&quot;&gt;Antes de la Actualizaci&oacute;n&lt;/b&gt; es altamente recomendable.&lt;br /&gt;&iexcl;Usted ha sido advertido!',
        'comment1' => 'Ruta de acceso a carpeta, &lt;b class=\&quot;warning\&quot;&gt;con barra final&lt;/b&gt;, donde las im&aacute;genes se guardar&aacute;n.&lt;br /&gt; <span id="result_box"><span title="">por ejemplo</span></span>: assets/gallery/.',
        'create_dir_err' => 'No se puede crear la carpeta',
        'create_err' => 'no ha sido creada.',
        'created' => 'ha sido creada con &eacute;xito.',
    'credit_lang_file' => 'Language file credit',
    	'credit_lang_file_author' => 'Cx2, Temus, goldsky, islander',
    'credit_lang_file_date' => 'October 6, 2010',
    'credit_lang_file_version' => '2.1',
    	'data' => 'Datos',
    	'data_updated_err' => ' datos no actualizados',
    	'data_updated_suc' => ' datos actualizado',
        'del_inst_dir' => 'Eliminar carpeta de instalaci&oacute;n',
        'dir_created' => 'La carpeta ha sido creada',
        'dir_exists' => 'La carpeta ya existe',
        'empty_dir' => 'carpeta no se establece',
        'field' => 'Campo',
        'mod_update_err' => 'No se puede actualizar el m&oacute;dulo',
        'mod_updated' => 'El m&oacute;dulo se ha actualizado',
        'ok' => 'Instalar',
        'path' => 'Ruta',
    	'plugin_added' => 'Plugin creado',
    	'plugin_add_err' => 'No se pudo agregar el plug-in',
        'rename' => 'nombre cambiado.',
        'rename_err' => 'nombre no ha sido cambiado.',
        'restore_err' => 'Ha habido un error al intentar restaurar',
        'restore_suc' => 'Nombres de las galer&iacute;as restaurada',
        'snippet_add_err' => 'No se puede crear el snippet',
        'snippet_added' => 'Ha sido creado el snippet',
        'snippet_update_err' => 'No se puede actualizar el snippet',
        'snippet_updated' => 'El snippet se ha actualizado',
    	'submit' => 'Guardar',
        'success' => 'Instalado con &eacute;xito',
	'system_check' => 'Comprobaci&oacute;n del sistema',
        'table' => 'Tabla',
    	'upgraded' => 'actualizado con &eacute;xito.',
        'upgraded' => 'actualizado con &eacute;xito.',
);