<?php
$e2g = array (
'dir' => 'assets/gallery/',
'maxw' => 1000,
'maxh' => 750,
'maxthq' => 86,
'w' => 140,
'h' => 140,
'thq' => 86,
'glib' => 'highslide',
'name_len' => 18,
'cat_name_len' => 18,
'colls' => 3,
'limit' => 9,
'orderby' => 'date_added',
'order' => 'DESC',
'cat_orderby' => 'cat_id',
'cat_order' => 'DESC',
'css' => 'assets/modules/easy2/templates/style.css',
'tpl' => 'assets/modules/easy2/templates/gallery.htm',
'dir_tpl' => 'assets/modules/easy2/templates/directory.htm',
'thumb_tpl' => 'assets/modules/easy2/templates/thumbnail.htm',
'rand_tpl' => 'assets/modules/easy2/templates/random_thumbnail.htm',
'comments_tpl' => 'templates/comments.htm',
'comments_row_tpl' => 'templates/comments_row.htm',
'ewm' => 0,
'wmtype' => 'text',
'wmt' => 'e2g',
'wmpos1' => 3,
'wmpos2' => 3,
'ecm' => 1,
'ecl' => 7,
);
?>